#!/bin/sh
#
# Start mdev....
#

case "$1" in
  start)
	echo /sbin/mdev >/proc/sys/kernel/hotplug
	/sbin/mdev -s &> /dev/null
	# coldplug modules
	find /sys/ -name modalias -print0 | xargs -0 sort -u -z | xargs -0 modprobe -abq
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
