#!/bin/sh

start() {
	X -s 0 -dpms -mouse mouse,,/dev/input/mouse0 -keybd evdev,,device=/dev/input/event0 $(cat /etc/x11args) &> /dev/null &
}

stop() {
	killall -9 X
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit 0
